window.tablesDatabase = window.tablesDatabase || [];

window.tablesDatabase.push({
    id: "items-table",
    title: "Chapter 4-3: Item Table",
    description: "Roll a d4 hundreds bracket and a d100 unit selector to generate random gear, loot, oddities, or dungeon debris.",
    type: "items-table",
    category: "exploration",
    entries: {
        // Range 1-99 (d4 = 4)
        1: "Hammer (PHB)", 2: "Sprung trap, rusted shut.", 3: "Record of a criminal trial trial parchment", 
        4: "Splintered club", 5: "Copper coin", 6: "Greatclub (Weapon, PHB)", 7: "Rusty armour", 
        8: "Mess kit (PHB)", 9: "Patch of moss", 10: "Rubble & debris", 11: "Broken weapon remnant", 
        12: "Net (Weapon, PHB)", 13: "Text on armour making", 14: "Cracks in the wall/floor/ceiling", 
        15: "The hilt of a dagger", 16: "Manacles (PHB)", 17: "Tattered loincloth", 18: "Fishing tackle gear", 
        19: "Damp, slick area", 20: "Bedroll (PHB)", 21: "Rubble & debris", 22: "Scattered caltrops", 
        23: "Iron arrowheads", 24: "Bar of soap", 25: "Backpack (PHB)", 26: "Old abacus", 
        27: "Broken pots / vases", 28: "Holy symbol (PHB)", 29: "Smear of dried blood", 
        30: "Rotting carcass of recent dead (animal/adventurer/previous inhabitant)", 31: "Decaying stores of food/equipment", 
        32: "Wooden chair", 33: "Healer's kit (PHB)", 34: "Ancient text on astrology", 35: "Animal dung", 
        36: "Rubble & debris", 37: "Cracked glass flask", 38: "Mouldy food scraps", 39: "Grappling hook (PHB)", 
        40: "Ransacked chest", 41: "Empty necklace pouch", 42: "Tiny, ticking music box", 43: "Sprouting fungi", 
        44: "Tuft of hair or fur", 45: "Longbow (Weapon, PHB)", 46: "Dented iron helmet", 47: "Single leather boot", 
        48: "Club (Weapon, PHB)", 49: "Old rest-site with old or recent bedrolls", 50: "Rotted creature's nest, with old eggshells/fledgeling bones in it.", 
        51: "A makeshift shrine", 52: "Rusty wood saw", 53: "Rubble & debris", 54: "Bag of 1000 ball bearings (PHB)", 
        55: "Faded text on brewing", 56: "Scattered leaves and twigs", 57: "Common green mould", 58: "Wooden pick handle", 
        59: "Druidic focus (PHB)", 60: "Text on exotic flora or fauna", 61: "Rusted metal file", 62: "Rusty nose ring", 
        63: "A small figurine with some burnt-out candles", 64: "Spikes, Iron x 10 (PHB)", 65: "Broken wooden pole", 
        66: "Pottery shards", 67: "Glass jar with a preserved animal", 68: "Soiled rags", 69: "Acid Vial (PHB)", 
        70: "A woven basket", 71: "Set of common clothes (PHB)", 72: "Rubble & debris", 
        73: "A cutting board with a small hunting knife stuck upright in it", 74: "Magnifying glass (PHB)", 
        75: "Decayed corpse", 76: "Training dummies with a couple of arrows sticking out", 77: "Flask of holy water (PHB)", 
        78: "Iron doorknocker", 79: "Torture rack apparatus", 80: "Navigational compass", 81: "Rubble & debris", 
        82: "Unexploded smoke bomb", 83: "Set of lockpicks", 84: "Dagger (Weapon, PHB)", 85: "Hunting trap (PHB)", 
        86: "Wire cutters", 87: "Rubble & debris", 88: "Wizard's Spell book (contains **[SUB_ITEM_SPELLBOOK]**)", 
        89: "A key (to a door in another dungeon perhaps?)", 90: "Rubble & debris", 91: "Unstrung lute", 
        92: "Spyglass (PHB)", 93: "Burnt-out torches (Q/A to find out what)", 94: "Wads of dirty hair and rags", 
        95: "Ink, bottle (PHB)", 96: "Component pouch (PHB)", 97: "Decayed hempen rope", 98: "Iron thumbscrews", 
        99: "Mirror, steel (PHB)",

        // Range 100-199 (d4 = 1)
        100: "Broken glass bottle", 101: "Torn burlap sack", 102: "Lance (Weapon, PHB)", 103: "Empty wooden barrel", 
        104: "Harmless translucent slime", 105: "Bloody cloth rags", 106: "Hourglass (PHB)", 107: "Scattered bones", 
        108: "Rotting wooden coffin", 109: "Heavy crossbow (Weapon, PHB)", 110: "Rubble & debris", 111: "Rusted iron spike", 
        112: "Crude wall graffiti", 113: "Shruncken head trophy", 114: "Stones of interesting colour/shape", 115: "Writing quill", 
        116: "Crossbow Bolt case (PHB)", 117: "Half-empty bottle of whisky", 118: "Tattered old hat", 119: "Broken sword blade", 
        120: "Teeth or fangs, scattered", 121: "Smoldering torch stub", 122: "Antitoxin vial (PHB)", 123: "Iron pliers", 
        124: "Stagnant puddle of water", 125: "Iron crowbar", 126: "Hammer, sledge (PHB)", 127: "Text on herbalism", 
        128: "Chipped clay plate", 129: "Wax blob (candle stub)", 130: "Empty belt pouch", 131: "Pieces of rotting wood", 
        132: "Alchemist's Fire (PHB)", 133: "Desiccated corpse", 134: "Tally marks scratched on a surface", 135: "Longsword (Weapon, PHB)", 
        136: "Old broken chair leg", 137: "Cold brazier & charcoal", 138: "Brazier & charcoal (lit and burning)", 139: "10 ft pole (PHB)", 
        140: "Wooden bucket", 141: "Ornate candelabrum", 142: "Localized regional map", 143: "Sprigs of fresh wolfsbane", 
        144: "Iron lock (PHB)", 145: "Small stone idol", 146: "Rolled up mat/rug", 147: "Hammer, sledge (PHB)", 
        148: "Rubble & debris", 149: "Faded text on mathematics", 150: "Wall sconce", 151: "Small oil painting", 
        152: "Hand crossbow (Weapon, PHB)", 153: "Technical text on masonry", 154: "Potion of Greater Healing", 155: "Glass eye replacement", 
        156: "Empty velvet purse", 157: "10 feet of iron chain (PHB)", 158: "Dried buds of garlic", 159: "Standard graffiti in orcish or dwarven script", 
        160: "Large pile of dung", 161: "Random paper with hastily-scribbled words and phrases", 162: "Cracked eggshells", 
        163: "Blowgun (Weapon, PHB)", 164: "Wooden packing crate", 165: "Faded historical text", 166: "Halberd (Weapon, PHB)", 
        167: "Folded burial shroud", 168: "Shedded snakeskin", 169: "Rope, hempen (50 ft.) (PHB)", 170: "Text on advanced masonry", 
        171: "Feather cushion", 172: "Lantern, bullseye (PHB)", 173: "Rubble & debris", 174: "Empty glass bottles", 
        175: "An assortment of **[1d10]** aromatic incense sticks", 176: "Dart (Weapon, PHB)", 177: "Small alcove shrine", 
        178: "Expired, cold torches", 179: "Iron cooking pot",

        // Range 200-299 (d4 = 2)
        200: "Handaxe (Weapon, PHB)", 201: "Shortbow (Weapon, PHB)", 202: "Fancy feathered hat", 203: "Blashemous heretical text", 
        204: "Sheets of blank parchment", 205: "Rope, silk (50 ft) (PHB)", 206: "Lichen growth", 207: "Oil of slipperiness (Magic Item, DMG)", 
        208: "Maul (Weapon, PHB)", 209: "Jar of healing salve or unguent", 210: "Hand drum percussion instrument", 211: "Standard rations (1 day) (PHB)", 
        212: "Clevly forged document", 213: "Climbing piton (PHB)", 214: "Needle & spool of thread", 215: "Cloth skullcap", 
        216: "Rubble & debris", 217: "Javelin (Weapon, PHB)", 218: "Goggles of Night (Magic Item, DMG)", 219: "Tome of forbidden lore", 
        220: "Bronze ceremonial gong", 221: "Unholy cult symbol", 222: "Ammunition case containing 20 crossbow bolts", 223: "Cryptic theological text", 
        224: "Flint and steel tinderbox (PHB)", 225: "Bundle of **[1d4]** sharpened wooden stakes", 226: "Serving tray", 227: "Empty cloth sack", 
        228: "Portable iron ram (PHB)", 229: "Ceramic soup tureen", 230: "Set of balancing scales & weights", 231: "Ink pen kit (PHB)", 
        232: "Chipped clay vase", 233: "Frayed twine rope", 234: "Greatsword (Weapon, PHB)", 235: "Rubble & debris", 
        236: "Travelogue manuscript for an exotic land", 237: "Language translation dictionary", 238: "Cured animal hide", 239: "Heavy wooden mallet", 
        240: "Sharpening whetstone", 241: "Scattered holy writings", 242: "Light Crossbow (Weapon, PHB)", 243: "Small pouch of sand", 
        244: "Last will and testament scroll", 245: "Perfume vial (PHB)", 246: "Set of wooden pan pipes", 247: "Small pouch of wild berries", 
        248: "Powdered cosmetic wig", 249: "Flail (Weapon, PHB)", 250: "Glass laboratory beaker", 251: "Blasphemous unholy writings", 
        252: "Ceremonial thurible censer", 253: "Sickle (Weapon, PHB)", 254: "Rubble & debris", 255: "Planar travelogue of the planes", 
        256: "Rotting corpse", 257: "Woven prayer rug", 258: "Book of local myths", 259: "Set of masquerade costume clothes (PHB)", 
        260: "Sealed wax letter", 261: "Forge bellows", 262: "Leather scroll case", 263: "Sling (Weapon, PHB)", 
        264: "Written ravings of a lunatic", 265: "Carved cryptographic runes", 266: "Full leather wineskin", 267: "Scale, merchant's weight kit (PHB)", 
        268: "Bronze incense burner", 269: "Burst, torn waterskin", 270: "Brass signal whistle (PHB)", 271: "Broken arrow shafts/bolts", 
        272: "Stick of sealing wax (PHB)", 273: "Personal diary ledger", 274: "Morningstar (Weapon, PHB)", 275: "Empty wooden bowl", 
        276: "Empty iron cage", 277: "Rubble & debris", 278: "Jar of mysterious colored beans", 279: "Standard Potion of Healing (PHB)", 
        280: "Iron brewing cauldron", 281: "Rubble & debris", 282: "Severed claw from a random beast", 283: "Lantern, hooded (PHB)", 
        284: "Plain traveling robes (PHB)", 285: "Tangled ball of string", 286: "Warhammer (Weapon, PHB)", 287: "Navigational star chart celestial wheel", 
        288: "Unrolled magic scroll", 289: "Ominous glass crystal ball", 290: "Light hammer (Weapon, PHB)", 291: "Glass wine decanter", 
        292: "Dried medicinal herbs", 293: "Empty glass vial (PHB)", 294: "Chalk drawn magic circle outline", 295: "Pick, miner's heavy tool (PHB)", 
        296: "Stone mortar & pestle set", 297: "Ceramic jug or pitcher", 298: "Rubble & debris",

        // Range 300-399 (d4 = 3)
        300: "Climber's Kit (PHB)", 301: "Roll of blank parchment sheets", 302: "One pound sack of salt", 303: "Dirty discarded rags", 
        304: "Scimitar (Weapon, PHB)", 305: "Hand drawn layout map", 306: "Stale bottle of tavern ale", 307: "Book of heraldry houses", 
        308: "Refractive glass prism", 309: "Standard adventuring torch (PHB)", 310: "Writing quill pen", 311: "Tooled strip of leather", 
        312: "Potion of Greater Healing (Magic Item, PHB)", 313: "Skeletal corpse remnant", 314: "Stick of white marking chalk", 315: "Whip (Weapon, PHB)", 
        316: "Dried fruit peel", 317: "Empty leather component pouch", 318: "Pike (Weapon, PHB)", 319: "Rubble & debris", 
        320: "Rolled up messaging scroll", 321: "Humanoid skull trophy", 322: "Battleaxe (Weapon, PHB)", 323: "Wax earplugs in a small pouch", 
        324: "Brass locket containing a faded portrait picture", 325: "Wooden smoking pipe", 326: "Dried, pressed flowers", 327: "Greataxe (Weapon, PHB)", 
        328: "Iron skeleton key", 329: "Glass vial filled with congealed blood", 330: "Silver measuring spoon", 331: "Pair of bone gaming dice", 
        332: "Full waterskin (PHB)", 333: "Leather horse's bridle harness", 334: "Rubble & debris", 335: "Jar containing a mysterious thick paste", 
        336: "Brass desktop hourglass", 337: "Copper tea kettle", 338: "Carved wooden flute", 339: "Leatherworker awl tool", 
        340: "Vial of Basic Poison (PHB)", 341: "Pool of dried vomit", 342: "Dusty bottle of fine wine", 343: "Bone gaming set tokens", 
        344: "Clean linen bandages", 345: "10 ft. wooden ladder (PHB)", 346: "Silver bristle hairbrush", 347: "Jar of lubricating grease", 
        348: "Set of fine aristocratic clothes (PHB)", 349: "Rubble & debris", 350: "Sheet music manuscript", 351: "Pouch of white cooking flour", 
        352: "Pouch of premium tobacco leaf", 353: "Bundle of loose bedding straw", 354: "Mace (Weapon, PHB)", 355: "Loaf of bread (unspoilt), wrapped in cloth", 
        356: "Polished animal drinking horn", 357: "Carved wooden child's toy", 358: "Small utility pocket knife", 359: "Rubble & debris", 
        360: "Rapier (Weapon, PHB)", 361: "Monster Bestiary codex volume", 362: "Corked bottle of honey mead", 363: "Empty tin cup", 
        364: "Frothing pewter tankard", 365: "Artificer Arcane Focus token (PHB)", 366: "Ceramic liquid flagon", 367: "Shortsword (Weapon, PHB)", 
        368: "Clerical prayer book manual", 369: "Potion of Superior Healing (Magic Item, PHB)", 370: "Unlit oil lamp (PHB)", 371: "Financial ledger book of accounts", 
        372: "Humanoid corpse carcass", 373: "Standard glass potion of healing vial", 374: "Clay jar filled with an unknown foul substance", 375: "Iron-tipped pitchfork", 
        376: "Crossbow bolt quiver (PHB)", 377: "Glaive (Weapon, PHB)", 378: "Feudal land property deed scroll", 379: "Iron candle snuffer tool", 
        380: "Polished wooden walking stick", 381: "Small velvet pouch of children's glass marbles", 382: "Rubble & debris", 383: "Potion of Healing store variant", 
        384: "Paper packet of exotic foreign cooking spice", 385: "Trident (Weapon, PHB)", 386: "Set of animal knucklebones", 387: "Driftglobe (Magic Item, DMG)", 
        388: "Pair of tailoring scissors", 389: "Culinary recipe book volume", 390: "Small ornate wooden casket box", 391: "Strand of wooden prayer beads", 
        392: "Standard glass Potion of Healing (PHB)", 393: "Small protective box of matches", 394: "Weathered skull of a humanoid creature", 395: "Official royal proclamation scroll", 
        396: "Iron soup ladle", 397: "Glass vial of aromatic cologne", 398: "Braided lock of human hair", 399: "Whetstone grooming file (PHB)"
    }
});