window.tablesDatabase = window.tablesDatabase || [];

// Sub-tables for embedded d10 skill check requirements
const subSkillTables = {
    physicalMental: [
        "Acrobatics / Dex check or save", "Strength or Athletics check", "Stealth check", 
        "Con check or save", "Int check", "Investigation check", "Arcana check", 
        "History check", "Nature check", "Religion check"
    ],
    socialWisdom: [
        "Animal Handling check", "Insight check", "Survival check", "Medicine check", 
        "Perception check", "Persuasion check", "Performance check", "Deception check", 
        "Intimidation check", "Charisma check"
    ]
};

window.tablesDatabase.push({
    id: "master-location-encounters",
    title: "Location Encounters Matrix",
    description: "Select your active gaming environment to roll localized d100 encounter threads.",
    type: "environment-matrix",
    subSkills: subSkillTables,
    environments: {
        Wilderness: [
            { min: 1, max: 4, result: "Small dungeon or crypt found. Purpose and history unknown. If entering, go to Chapter 8: Random Dungeon Generation." },
            { min: 5, max: 5, result: "Ready-made camp found, or cosy cave, that could potentially be used as shelter for the night, or a base while exploring. Inhabited?" },
            { min: 6, max: 6, result: "A small creek, babbling pleasantly. Or a large crack, bubbling pungently." },
            { min: 7, max: 7, result: "A storm on the horizon, lightning dancing underneath dark grey clouds." },
            { min: 8, max: 8, result: "A sinkhole has opened up nearby." },
            { min: 9, max: 10, result: "Abandoned, empty town." },
            { min: 11, max: 15, result: "NPC met, who gives PC information about possible quest. Go to Chapter 7 and generate a quest, which you may or may not choose to accept." },
            { min: 16, max: 16, result: "Abandoned campsite found. Use Q/A rolls to find out more." },
            { min: 17, max: 17, result: "A tree with what looks like Druid markings." },
            { min: 18, max: 18, result: "You find survivors of some sort of attack, and they have a tale to tell..." },
            { min: 19, max: 19, result: "Plundered barrow / burial mound. But did they get everything? And what still waits there? (50% mostly empty)" },
            { min: 20, max: 20, result: "On the road, a dropped item. A backpack, a purse with interesting contents / a hat with a note tucked inside / an engraved ring… could be anything. Use Q/A roll to find out details." },
            { min: 21, max: 21, result: "Interesting traveller. This character has obviously seen some things..." },
            { min: 22, max: 22, result: "Cemetery. Some of the graves have been looted, and most of the tombstones are so old that the names have worn off." },
            { min: 23, max: 23, result: "Prisoner(s) being escorted in a heavily-armoured cart." },
            { min: 24, max: 24, result: "Interesting geological feature. Use Q/A mechanic to find out what." },
            { min: 25, max: 25, result: "You find a discarded backpack with some intriguing contents." },
            { min: 26, max: 26, result: "An odd noise is coming from some distance ahead..." },
            { min: 27, max: 27, result: "Strange lights in the nearby hills are attracting your attention." },
            { min: 28, max: 28, result: "You stumble across an orchard, filled with ripe and delicious fruit. The owner is nowhere in sight." },
            { min: 29, max: 29, result: "Bounty hunters, searching for a fugitive. “You seen anyone?” (Who they are working for is unclear)" },
            { min: 30, max: 30, result: "Sudden and abrupt change in weather." },
            { min: 31, max: 31, result: "Abandoned mine, dwarven or otherwise." },
            { min: 32, max: 32, result: "You hear howling in the distance. It could be wolves, but the sound is strange somehow..." },
            { min: 33, max: 33, result: "Debris from a recent, large battle. Who fought here, and who won? How recent was this?" },
            { min: 34, max: 34, result: "Humanoid corpse. 25% chance you find a clue (see Clue table in Chapter 9)." },
            { min: 35, max: 35, result: "A bird (or some other creature – roll Creature Table Chapter 14) begins talking to you, in fluent Common! And not just mindless parroting..." },
            { min: 36, max: 36, result: "A royal/noble personage and their entourage passes in an opulent carriage." },
            { min: 37, max: 37, result: "A flock of birds (vultures? ravens?) circles over a point somewhere overhead." },
            { min: 38, max: 38, result: "You find an old, ruined monument. Is it to a god, a famous local figure, or something else?" },
            { min: 39, max: 39, result: "A traveller with information/warning about a situation in the next settlement." },
            { min: 40, max: 40, result: "Unmarked settlement: town/village/hamlet. Human?" },
            { min: 41, max: 41, result: "You reach a bridge over a small river. The bridge is washed out. Travellers are waiting here, unsure what to do." },
            { min: 42, max: 42, result: "You find an injured beast." },
            { min: 43, max: 43, result: "A farmer invites you into his house for a meal, and possibly some of his home brew ale/mead as well." },
            { min: 44, max: 44, result: "Overturned/broken-down cart. Is it attended?" },
            { min: 45, max: 50, result: "Monster ambush. Level-appropriate easy encounter. Go to Chapter 16." },
            { min: 51, max: 51, result: "An animal wanders across your path. It glances up at you but doesn’t seem particularly bothered by your presence." },
            { min: 52, max: 52, result: "Trapped creature (humanoid? monster? What type of trap?)" },
            { min: 53, max: 55, result: "An abandoned/ruined structure of some kind, which may or may not have a subterranean component." },
            { min: 56, max: 56, result: "An old hermit. What’s he babbling about?" },
            { min: 57, max: 57, result: "A creepy and unsettling token/sign." },
            { min: 58, max: 58, result: "Traveling merchant." },
            { min: 59, max: 59, result: "A traveling adventurer who is impressed and wants to join your party." },
            { min: 60, max: 65, result: "Monster Encounter: Level-appropriate medium encounter. Go to Chapter 16." },
            { min: 66, max: 66, result: "A traveller, resting by the side of the road, begins pointing and laughing uproariously at you. Is she mad?" },
            { min: 67, max: 67, result: "Heavily-guarded transport passes." },
            { min: 68, max: 68, result: "Travelling sage/archivist." },
            { min: 69, max: 69, result: "Bandits (human or otherwise) demand a toll from you." },
            { min: 70, max: 75, result: "Monster: Level appropriate hard encounter." },
            { min: 76, max: 76, result: "A starving family begging for food or gold." },
            { min: 77, max: 77, result: "A tribe who owns the land demands a tribute from you for passage (and in return will escort you through – whether you like it or not)." },
            { min: 78, max: 78, result: "A travelling troupe of performers (80% Friendly)." },
            { min: 79, max: 79, result: "A travelling merchant, but his wares are not the ordinary. Indeed, much of it is illegal in some way. Is he a smuggler? A drug dealer? A heist thief?" },
            { min: 80, max: 80, result: "Hunters/travellers/adventurers. Camped up and relaxing." },
            { min: 81, max: 81, result: "You see a low rocky hill, where faces have been carved into the rocks, along with the shapes of various beasts. It is artfully done, and seems to tell some sort of story." },
            { min: 82, max: 82, result: "You see a track leading away from the road and into the forest/hills. Who knows where it leads..." },
            { min: 83, max: 83, result: "Bandits waylay you and demand all your money." },
            { min: 84, max: 84, result: "On a lonely stretch of road, you see a lone cabin, but cannot tell if it is inhabited or not." },
            { min: 85, max: 85, result: "A long-forgotten battlefield. How many died here?" },
            { min: 86, max: 86, result: "A tower, visible off the road some distance." },
            { min: 87, max: 87, result: "Patrol from the nearest settlement." },
            { min: 88, max: 88, result: "Unmarked settlement." },
            { min: 89, max: 89, result: "The road disappears and the place looks nothing like on the map." },
            { min: 90, max: 94, result: "NPC appears with quest. (Use Chapter 7)." },
            { min: 95, max: 100, result: "Monster! Level-appropriate encounter. [Sub-roll d4: 1-3 = Hard, 4 = Deadly]" }
        ],
        Dungeon: [
            { min: 1, max: 5, result: "Something occurs, or you find something, that requires a physical/mental check: **[SUB_SKILL_1]**. Use Q/A rolls or Story Element Interaction tables (chapter 14) to find out what." },
            { min: 6, max: 10, result: "Something occurs, or you find something, that requires a social/wisdom check: **[SUB_SKILL_2]**. Use Q/A rolls or Story Element Interaction Tables (chapter 14) to find out what." },
            { min: 11, max: 15, result: "NPC gives you information about possible quest. Go to Chapter 7 and generate a quest, which you may or may not accept. (Generate NPC as well – Chapter 13)." },
            { min: 16, max: 20, result: "Monster: Level-appropriate easy encounter. Go to Chapter 16." },
            { min: 21, max: 25, result: "Monster: Level-appropriate medium encounter. Go to Chapter 16." },
            { min: 26, max: 30, result: "Level appropriate hard encounter. Go to Chapter 16." },
            { min: 31, max: 35, result: "Level appropriate deadly encounter. Go to Chapter 16. Your PC might want to flee!" },
            { min: 36, max: 36, result: "Dead beast or monster carcass. What happened here?" },
            { min: 37, max: 37, result: "You find a strange growth in this area, on the dungeon walls. Is it a moss of some kind?" },
            { min: 38, max: 38, result: "Part of the floor has crumbled away, revealing a black, empty space below." },
            { min: 39, max: 39, result: "A door covered in moss, with a large knocker. Looks like it’s been transplanted here from someone’s garden." },
            { min: 40, max: 40, result: "You enter a tomblike area. All of the coffins are child-sized." },
            { min: 41, max: 41, result: "Strange vines have grown all through here, creeping around the stonework and gradually, over time, destroying parts of the masonry. How did they get in here?" },
            { min: 42, max: 42, result: "You see a statue of a wizard in the middle of this area. The plaque beneath reads “I am Fennishaw Eldsight. Speak my name and bring me to life, if you dare!”" },
            { min: 43, max: 43, result: "You hear voices ahead, and turn the corner to see a barbarian parleying with an ogre! Apparently they are discussing what the ogre’s price is for releasing the half-orc he is currently holding hostage." },
            { min: 44, max: 44, result: "A voice repeatedly whispers, “What do you seek?” No matter how you respond, it repeats the same question. (Perhaps until you give the true answer, at which point, you may get what you seek, but not as you expected!) Who does this voice belong to, if anyone?" },
            { min: 45, max: 45, result: "The ceiling above you opens, and an unexpected NPC falls through screaming, hitting the ground in front of you! Roll NPC Tables to find out who it is." },
            { min: 46, max: 46, result: "This area is home to a mining operation. Enslaved humanoid children are toiling away, loading rocks into mine carts for ore processing. Their masters whip and force them to continue on, despite their obvious fatigue." },
            { min: 47, max: 47, result: "A middle-aged woman is slumped against the wall, sobbing. She is dressed in rags." },
            { min: 48, max: 48, result: "From nowhere, you hear a booming voice: “Take up your weapon, adventurer! You dare to trespass here, now you will face me in battle!” But no one appears. At least not yet… You hear laughing..." },
            { min: 49, max: 49, result: "Suddenly a vision flickers before you, a vision of your ultimate goal in this dungeon. You do not recognize the room, but get some prior information about what you might be headed towards." },
            { min: 50, max: 55, result: "TRAP! Roll on Traps table to find out what." },
            { min: 56, max: 56, result: "Graffiti on the wall: “Stop! Bridge out ahead! Go back, your doom is at hand!”" },
            { min: 57, max: 57, result: "Nearby, you hear a dog barking madly, then another voice telling it to shut up!" },
            { min: 58, max: 58, result: "You hear screaming, very faint, as if from far, far away." },
            { min: 59, max: 59, result: "You round the next corner and see two humanoids engaged in a heated quarrel." },
            { min: 60, max: 60, result: "Make a perception check, DC 14. If unsuccessful, you suddenly notice your pack is lighter. Randomly choose one item from your inventory (perhaps figure out a way to randomly roll for it). It has been stolen! You might get it back, but then again..." },
            { min: 61, max: 61, result: "You come to a door on which a parchment is nailed. “Dungeon caretaker. Enquiries/complaints within.”" },
            { min: 62, max: 62, result: "Suddenly the wall behind you explodes, and two adventurers enter through it. One is a goliath who has just punched his way through the masonry, the other appears to be a halfling sorcerer." },
            { min: 63, max: 63, result: "Ahead, two orc guards sit at a guard post. They appear to be playing dice." },
            { min: 64, max: 64, result: "A giant rat runs past you, closely followed by three hungry-looking goblins. They pay you no attention." },
            { min: 65, max: 65, result: "As you move through this area, make a perception check, DC 15. If you fail, you do not see a glyph on the wall and trigger an alarm spell! What comes to check?" },
            { min: 66, max: 66, result: "In a corner, a huge pile of rubbish festers. It is being picked through by some horrid beast or other." },
            { min: 67, max: 67, result: "You get the distinct impression that you are being followed. You even fancy you can smell whoever it is, and they smell rank." },
            { min: 68, max: 68, result: "You happen upon a massacre. The corpses of a dozen humanoids lie scattered." },
            { min: 69, max: 69, result: "A mist swirls about your feet." },
            { min: 70, max: 70, result: "You feel a hard shove in your back. When you turn to look, is anyone there?" },
            { min: 71, max: 71, result: "Roll perception, DC 14. If successful you notice something in your periphery. A stone in the wall shuts with a scrape. Investigation roll, DC 12, to find the mechanism to open it. Beyond is a (d4) 1-2: passage, 3-4: room, containing an encounter (d4) 1: Easy, 2: Medium, 3: Hard, 4: No encounter. Clue 75%, Individual Loot 50%." },
            { min: 72, max: 72, result: "An old timer, clearly mad, is perched on a soapbox to the side of this passage, ranting about the current state of political affairs to an audience of one slightly amused boggart." },
            { min: 73, max: 73, result: "As you round the next corner, you catch sight of a lone humanoid. Make a stealth check, DC 14. If successful, you stay hidden and watch as they move a stone in the wall, place something behind it, then replace the stone. Then they depart." },
            { min: 74, max: 74, result: "You come across a proper dungeon - a locked room with bars, in which you see several ragged-looking prisoners. “Quick, break us out!” one of them exclaims when he sees you." },
            { min: 75, max: 75, result: "You come across an ornate door, attended by a spectral figure dressed in opulent clothes. The thing is non-hostile, and manning this door, like a doorman. Roll a d4. On a 1: He praises you and your obvious prowess as an adventurer. He seems to know a lot. The spectral doorman opens the door for you. On a 2: He begins insulting you, pointing out how awful your clothes are, how ugly you are, how terrible you smell! Make a wisdom check, DC 15. If you succeed, he congratulates you on your poise in the face of abuse and lets you through the door. On 3-4: He begins debating with you as to why you shouldn’t be admitted through the door. Make an intelligence check or a persuasion check, DC 14. If successful, you win the debate and he lets you through the door. The spectral doorkeeper cannot be attacked or moved. And the door only opens for him. (40% boss encounter)." },
            { min: 76, max: 76, result: "A kindly little goblin appears with hat in hand, and begs your help in ridding him of a problem. He has just returned from a trip to the nearest town to find that his home has been taken over! Two levels down, his humble little abode that he shares with his wife and two little goblings, has been invaded by a horrible level-appropriate hard encounter. If he could get your assistance in getting rid of this scourge, he will reward you with all his profits from his recent sales trip - 250 gp! And his wife will cook you a delicious pot of Tunnelslug Stew, finest in the dungeon, they say!" },
            { min: 77, max: 77, result: "You run into some rival adventurers, who happen to be there following the same leads as you. Will you team up with these NPCs? (Use NPC tables to determine who they are, skipping Profession and going straight to Class Tables)." },
            { min: 78, max: 78, result: "You take one more step and… boom! You are in an utterly unfamiliar part of the dungeon. Abandon the map you have so far. You have stepped through a portal, and now are not even sure you are in the same dungeon, realm, or world! Where have you been transported?" },
            { min: 79, max: 79, result: "You find a secret entrance to an opulent room, lined with bookshelves. A fire crackles in the hearth, and richly-patterned rugs and furniture decorate this cosy space. Who lives here?" },
            { min: 80, max: 80, result: "You find small circular openings in the walls. Each contains a scroll. Withdrawing them, you see that they bear writing from some ancient civilization. These could be of great worth to an archaeologist, but first you will need to get them translated. [Sub-roll d8: 1: Infernal, 2: Abyssal, 3: Celestial, 4: Draconic, 5: Druidic, 6: Giant, 7: Primordial, 8: Undercommon]. If you happen to speak the resultant language, use Q/A rolls to determine what they contain." },
            { min: 81, max: 81, result: "1d4-1 humanoids are arguing and do not notice your approach. One is a commander, the other(s) subordinate. The subordinate has failed in the execution of some task. If you choose to attack, this will be a (d4) 1: Easy, 2-3: Medium, 4: Hard encounter. Individual loot 50% (roll twice, once for each humanoid)." },
            { min: 82, max: 82, result: "You find the shrine of a long-forgotten deity. (Loot Hoard 30%). Perhaps this deity tries to commune with you, attempting to find a new worshipper?" },
            { min: 83, max: 83, result: "You see an ornate historical mural on a nearby wall, faded but obviously painted / carved by a master artist. As you watch, the figures in the mural come to life and begin to play out a scene hitherto unknown to you. You gain knowledge of this episode of history, and possibly of some previously undiscovered location/quest/relic associated with it." },
            { min: 84, max: 84, result: "You enter a chamber where a sacrificial ceremony is taking place. Several humanoids are gathered around a plinth, about to sacrifice a live beast. Who knows what the outcome of this ritual will be?" },
            { min: 85, max: 85, result: "You get the feeling you are being stalked by something, some invisible force. You see shadows, hear noises, feel a presence, but every time you turn you see nothing. Perhaps it will show itself eventually." },
            { min: 86, max: 86, result: "In the next room, a gnome sits at a table in a sparse room before a chess board. He invites you to play. Playing requires a DC 15 deception or intelligence check. If successful, the gnome will gift you with a useful trinket of gnomish invention, or 50 gp. If unsuccessful, you surrender an item of 50 gp worth." },
            { min: 87, max: 87, result: "You find an underground tavern, where dungeon denizens like to stop and get an ale every now and then before returning to their murderous exploits! It’s called The Delver’s Rest and the patronage is steady!" },
            { min: 88, max: 88, result: "You find a secret door to a chamber where an alchemist is busy preparing potions and tinctures of all kinds. He might be open to bartering, but is currently trying to prepare something that will “stop all hell breaking out in this place.”" },
            { min: 89, max: 89, result: "You find a dimensional door into a forest, but can’t be sure if this wilderness is real, or simply an illusion to lead you into even greater danger." },
            { min: 90, max: 90, result: "In this area are some pools of greyish-green slime of unknown nature. Q/A and nature rolls to determine more about their nature." },
            { min: 91, max: 91, result: "If the party are holding torches, or there are torches or candles present in the area, something blows them all out suddenly." },
            { min: 92, max: 92, result: "The area is filled with a thick mist/fog, that hangs heavy and low to the ground." },
            { min: 93, max: 93, result: "In the distance a small girl dressed in rags can be seen standing near the wall. If players move toward her, she will turn and run through the nearest wall and disappear." },
            { min: 94, max: 94, result: "To the far side three skeletons hang on manacles, if they are inspected 1d6 rats will jump out at the PCs." },
            { min: 95, max: 95, result: "The ground here is earthen and covered with a top soil. It smells heavily of must and dirt. Root-like tendrils will start to appear out of the ground and start to grow up the walls." },
            { min: 96, max: 96, result: "A player is bitten on the hand (causing minimal if no damage). What did it?" },
            { min: 97, max: 97, result: "A low rumble, then a deep cracking noise is heard directly above. The area shakes slightly, dust and small debris falls from the ceiling, then it stops." },
            { min: 98, max: 98, result: "A bard has stopped in this area to belt out a quick song to try and lift his own spirits. He’s been lost down here for days! He's absolutely starving, having had to subsist on dungeon moss and tunnelslugs for weeks." },
            { min: 99, max: 99, result: "You hear the sound of something heavy being dragged, coming from up ahead." },
            { min: 100, max: 100, result: "A large group of humanoids comes running down the tunnel towards you, their expressions showing absolute, abject terror. “RUN!” the lead one yells at you. “Save yourself, run, now!!!” Behind them, you see something BIG following..." }
        ],
        Urban: [
            { min: 1, max: 1, result: "You witness a crime and have a chance to stop the criminal. If you do, you win the favor of the local constabulary. If you try to but fail, the guard gives you an opportunity to help track down the criminal. If you do nothing, you must convince the guard you are not an accomplice." },
            { min: 2, max: 2, result: "Stampede of pigs." },
            { min: 3, max: 3, result: "A cry rings out through the town. “An army is massing outside the gates!” Are they human, orc, mind flayer? You had better go and find out, or flee right now!" },
            { min: 4, max: 4, result: "A mysterious hooded beggar conspicuously ducks into an alley as they walk by - they appeared to have a disfigurement. Perhaps they were just trying to hide from people." },
            { min: 5, max: 5, result: "A guided tour proceeds past, as the guide drops a particularly tasty snippet of local knowledge which the PC was unaware of." },
            { min: 6, max: 6, result: "A shady figure beckons from an alley. They have wondrous items for sale, they say." },
            { min: 7, max: 7, result: "Two old ladies, witches of some sort by the look of them, beg you to take a creature off their hands. “It never shuts up! Please, we’ll pay you! We just want to be rid of the damned thing!” The creature is the trapped soul of a former adventurer..." },
            { min: 8, max: 8, result: "Two men are arguing about something. One turns to a PC and says, 'You look like a reasonable man. What do you think?' Could be literally anything at all, and could result in combat, a job, or just more arguing." },
            { min: 9, max: 9, result: "Quest board with rewards for deeds done. Someone has rats in their cellar, missing townsperson in the woods nearby, simple things (or complex!) that keep you exploring the city, making contacts, and earning gold/interesting items." },
            { min: 10, max: 10, result: "A card shark/con artist is busking in the street, a large crowd gathers." },
            { min: 11, max: 11, result: "Two local thugs are strong-arming a merchant for gold. You can help the merchant, but doing so annoys the local gang. Variation: The merchant is a thief, and the thugs are trying to recover their stolen money." },
            { min: 12, max: 12, result: "You notice a group of villagers attempting to put out a nearby house fire. This looks like it could easily spread to neighbouring houses, possibly affecting the whole town." },
            { min: 13, max: 13, result: "A peddler attempts to sell you a trinket or minor magic item." },
            { min: 14, max: 14, result: "A giant rat crawls out of a storm drain and gets into a fight with a dog." },
            { min: 15, max: 15, result: "Minor earthquake shakes things up and in the ensuing panic looters take advantage. Does the party join them, or stop them?" },
            { min: 16, max: 16, result: "Merchant asking for help stopping local children with slingshots." },
            { min: 17, max: 17, result: "A young urchin is in an alley, cornered by either thugs or stray dogs." },
            { min: 18, max: 18, result: "Street is having a block party tomorrow and need help setting up." },
            { min: 19, max: 19, result: "Someone sentenced to death: You happen across the hanging/beheading scene before it concludes, what do you do?" },
            { min: 20, max: 25, result: "Monster: Level appropriate easy encounter." },
            { min: 26, max: 26, result: "A con man is selling jewels and rare components that you might need." },
            { min: 27, max: 27, result: "A chamber pot is emptied from above. Make a DC 13 dex save to avoid. If unsuccessful, you have disadvantage on all charisma and stealth related rolls until you have a bath and change clothes. (Optional: make a con save vs filth fever)." },
            { min: 28, max: 28, result: "A scrap of paper is pressed into your hand by a young man, who looks at you desperately before turning and running away. You turn over the note and read it. “Please help, he’s coming for us all!”" },
            { min: 29, max: 29, result: "A member of the local guard asks you what your business is in town." },
            { min: 30, max: 30, result: "“Stop, thief!” You feel your arms being grabbed. The local guard apprehend you, accusing you of stealing jewels belonging to a noble/royal. Searching your clothes, and/or bag, they successfully turn up the jewels in question. You, however, have never seen them before." },
            { min: 31, max: 31, result: "A lady / young man on a balcony blows you a kiss and then runs away." },
            { min: 32, max: 32, result: "A beggar crouches in a dark corner, clearly diseased." },
            { min: 33, max: 33, result: "Someone mistakes you for a mercenary, famous performer, or an old friend. They have face blindness. 2% of the population have it." },
            { min: 34, max: 34, result: "A bard strikes up a song and starts following you around." },
            { min: 35, max: 35, result: "A beggar notices the group and offers to guide them around in exchange for coin." },
            { min: 36, max: 36, result: "Bar fight bursts out into the street and may involve the PC." },
            { min: 37, max: 37, result: "Propositioned. Person of the night propositions a player. But they may not be all they seem..." },
            { min: 38, max: 38, result: "A drunkard sees you and mistakes you for friends or enemies or perhaps throws up on you." },
            { min: 39, max: 39, result: "A person who claims to be a fan of the PC begins to follow them around." },
            { min: 40, max: 40, result: "Snake Oil Salesman has gathered a crowd, and has actors in the group to fool people into buying worthless potions. Bonus: they're not worthless, but definitely not as advertised. A healing potion that's really gaseous form?" },
            { min: 41, max: 41, result: "Group of smugglers coming out of a sewer grate with a crate of goods." },
            { min: 42, max: 42, result: "An old female fortune teller beckons to you from her tent." },
            { min: 43, max: 43, result: "A man tumbles out a tavern window. He’s fully dressed in nobleman’s garb. A female half-orc jumps out after him, letting out a warcry as he gets up and runs for his life screaming for help. Do you help her and run him down or do you get in her way?" },
            { min: 44, max: 44, result: "A street dog runs past with a human hand in its mouth - wearing a large, very obvious jeweled ring. Dog chase or find out what happened to the owner of the ring (and hand)." },
            { min: 45, max: 45, result: "Someone's horse is spooked and charges through the streets. Whether it’s dragging a wagon or just a rider, it is panicked and needs to be stopped." },
            { min: 46, max: 46, result: "You find a map, discarded, on the street, or just a fragment of one, which arouses your curiosity. It shows a ruin, and there is a sketch of an artifact. Magical? Perhaps a local mage could help you decode this..." },
            { min: 47, max: 47, result: "A drunk just wakes up nearby. “Wha… where am I?! My… my weapons! My belongings! They’re gone!”" },
            { min: 48, max: 48, result: "You stop to listen to a talented storyteller relate a story about a famous adventurer and his beast companion. Part of the story is unresolved, however, and gets you thinking..." },
            { min: 49, max: 49, result: "You feel a thwack in the side of your head, and turn to see that a bunch of drunk young nobles are pelting passers by with rotten vegetables, laughing as they do so!" },
            { min: 50, max: 55, result: "Monster: Level appropriate medium encounter." },
            { min: 56, max: 56, result: "Your sharp eye spots a pickpocket deftly relieve a noblewoman of an expensive necklace." },
            { min: 57, max: 57, result: "A wizard is carrying a bagful of potions when suddenly the bag rips and several potions drop out and smash on the ground, exploding with various dramatic effects." },
            { min: 58, max: 58, result: "A jeweller emerges from his shop, screaming that he’s been robbed by dwarves. A nearby dwarf asks him for proof, but all he has to say is, “Of course it’s dwarves, they lust after gems constantly!”" },
            { min: 59, max: 59, result: "A female priest is castigating a businesswoman who has set up her wares before the temple. Except this business is no ordinary business - a female slaver is parading her wares, selling slaves to whoever’s buying." },
            { min: 60, max: 62, result: "Something occurs, or you find something, that requires a physical/mental check: **[SUB_SKILL_1]**. Use Q/A rolls or Story Element Interaction tables (chapter 14) to find out what." },
            { min: 63, max: 65, result: "Something occurs, or you find something, that requires a social/wisdom check: **[SUB_SKILL_2]**. Use Q/A roll or Story Element Interaction tables (chapter 14) to find out what." },
            { min: 66, max: 69, result: "NPC met, who gives PC information about possible quest. Go to Chapter 7 and generate a quest, which you may or may not accept." },
            { min: 70, max: 75, result: "Monster: Level-appropriate hard encounter. Monster on the loose, marauding through the streets." },
            { min: 76, max: 76, result: "You are stopped by the local guard who want to congratulate you on your recent successful quest. How do they know?" },
            { min: 77, max: 77, result: "PC hears a rumour about a job that a local priest might have. Apparently, or so the rumour goes, something is going on in the sacred catacombs beneath the streets." },
            { min: 78, max: 78, result: "You pass a house which is all boarded up, the gates locked. A passerby informs you that this is the house of a local nobleman who hasn’t been seen in years." },
            { min: 79, max: 79, result: "You see a dice game going on in an alley off the street you are walking down." },
            { min: 80, max: 80, result: "A cleric stands atop a box on the roadside, spouting vitriol and nasty rumours about the town’s leader or leaders. The cleric has attracted quite a crowd." },
            { min: 81, max: 81, result: "A group of protestors has set up outside the Town Hall, protesting the new road which is planned to run right through the middle of their settlement, some distance out of town." },
            { min: 82, max: 82, result: "A merchant asks you to mind his cart for him while he chases a thief who has stolen merchandise from it. He then leaves, and doesn’t return for a very long time..." },
            { min: 83, max: 83, result: "A street urchin appears, promising divine favour if the PC comes and volunteers an hour of service at a nearby temple." },
            { min: 84, max: 84, result: "A shopkeeper is attacking a wasp nest outside of his shop with a broom. He dislodges it and it crashes to the ground, engulfing him in a Swarm of Insects!" },
            { min: 85, max: 85, result: "Two half-orcs are engaged in a full-on brawl outside a nearby tavern. Apparently one thinks the other cheated at dice." },
            { min: 86, max: 86, result: "Religious pilgrims making their way quietly through the streets are being mocked and jeered by a group of elven teenagers." },
            { min: 87, max: 87, result: "A tattered cloak blows up the street. Catching hold of it, you find a note in one of its pockets." },
            { min: 88, max: 88, result: "Someone has released a hallucinogenic substance into the air, and people are in various states of intoxication." },
            { min: 89, max: 89, result: "A distraught mother cannot find her child and is convinced it has been kidnapped. She is moving from person to person, begging for help." },
            { min: 90, max: 90, result: "A sudden gust of wind whips through the town, sending stalls toppling over, hats flying, stacks of parchment fluttering down the street." },
            { min: 91, max: 91, result: "A dwarf, armed with greataxe, is threatening a cowering halfling, who is shaking with fear. The dwarf is living with rage, but has just been disarmed by the town guard." },
            { min: 92, max: 92, result: "An overturned cart ahead is causing gridlock - the street is jammed with traffic." },
            { min: 93, max: 93, result: "“Ay oop luv, looking for a good time?” A prostitute (any sex or race) begins soliciting you earnestly." },
            { min: 94, max: 94, result: "Suddenly, out of the blue, you see a mage of some sort simply appear in the middle of the street/alley." },
            { min: 95, max: 99, result: "NPC appears with quest (see Chapter 7)." },
            { min: 100, max: 100, result: "Monster: Level appropriate deadly encounter." }
        ]
    }
});