window.tablesDatabase = window.tablesDatabase || [];

window.tablesDatabase.push({
    id: "quest-generator",
    title: "Dynamic Quest Generator",
    description: "Rolls a dual-d100 array to simultaneously generate a core plot objective and the vector through which the party discovers it.",
    type: "combo-quest",
    problems: [
        { min: 1, max: 4, problem: "Unjust killing", quest: "Revenge" },
        { min: 5, max: 8, problem: "Crime committed, criminal disappeared", quest: "Apprehend / Bounty Hunt" },
        { min: 9, max: 12, problem: "Item lost", quest: "Retrieval" },
        { min: 13, max: 16, problem: "Tyrant(s) threaten town / business / population (monster / humanoid)", quest: "Repel / Sabotage / Deceive / Extort / Entrap" },
        { min: 17, max: 20, problem: "Environmental disturbance / Strange Weather / Infestation / Plague", quest: "Investigate / Solve" },
        { min: 21, max: 24, problem: "Magical chaos / Curse", quest: "Investigate / Lift curse / destroy magic" },
        { min: 25, max: 28, problem: "Kidnapping / Hostage situation", quest: "Rescue / Recover" },
        { min: 29, max: 32, problem: "Adventurer left some time ago, but is lost", quest: "Rescue" },
        { min: 33, max: 36, problem: "Something is rumoured, but undiscovered (Artefact, legendary place)", quest: "Explore / Discover" },
        { min: 37, max: 40, problem: "Riches rumoured within secure, guarded place", quest: "Loot" },
        { min: 41, max: 44, problem: "Invasion", quest: "Repel / Divert" },
        { min: 45, max: 48, problem: "Person suspected of something", quest: "Spy / Gather information" },
        { min: 49, max: 52, problem: "Important item / message / person needs transporting", quest: "Transport / smuggle / escort" },
        { min: 53, max: 56, problem: "Nefarious / dangerous item being transported", quest: "Waylay / Hijack" },
        { min: 57, max: 60, problem: "Dangerous item exposed / up for grabs", quest: "Find / Destroy" },
        { min: 61, max: 64, problem: "Corrupt noble", quest: "Investigate / Implicate / Incriminate / Expose" },
        { min: 65, max: 68, problem: "Commodity shortage (goods, workforce)", quest: "Transport supplies" },
        { min: 69, max: 72, problem: "Mystery unresolved", quest: "Research / Explore / Decode" },
        { min: 73, max: 76, problem: "Adventurer thrown into life-threatening situation (environmental or otherwise)", quest: "Survive" },
        { min: 77, max: 80, problem: "Worthy creature’s life threatened (humanoid / animal / monster)", quest: "Protect, eliminate threat" },
        { min: 81, max: 84, problem: "Execution of innocent party planned", quest: "Prevent" },
        { min: 85, max: 88, problem: "Siege (from a small party of goblins surrounding a farmhouse to an army of Imperial Blades surrounding a city!)", quest: "Break" },
        { min: 89, max: 92, problem: "Huge battle about to erupt", quest: "Negotiate / Prepare / Mediate / Participate" },
        { min: 93, max: 96, problem: "Spiritually beneficial place rumoured", quest: "Visit / Gain boon" },
        { min: 97, max: 100, problem: "Foolish individual committed innocent blunder", quest: "PC hired to conceal evidence / Return item / Placate" }
    ],
    sources: [
        { min: 1, max: 3, source: "Notice board" },
        { min: 4, max: 6, source: "NPC directly approaches" },
        { min: 7, max: 9, source: "Tavern rumour overheard" },
        { min: 10, max: 13, source: "Stumble blindly into the situation" },
        { min: 14, max: 16, source: "Guild affiliate contract assignment" },
        { min: 17, max: 19, source: "Fellow adventurer sharing a lead" },
        { min: 20, max: 22, source: "Mysterious scroll found containing explicit information" },
        { min: 23, max: 25, source: "Hidden piece of paper tucked inside a basic reward / item purchased" },
        { min: 26, max: 28, source: "An old treasure map discovered" },
        { min: 29, max: 31, source: "Found journal belonging to a missing owner" },
        { min: 32, max: 34, source: "Fragment of a partial map" },
        { min: 35, max: 37, source: "An unexpected inheritance (estate property, a strange item, or family title)" },
        { min: 38, max: 40, source: "Targeted Geas or mystical Quest Spell constraint" },
        { min: 41, max: 43, source: "Unholy, invasive visions during rest" },
        { min: 44, max: 46, source: "A lost map or letter uncovered in old archives" },
        { min: 47, max: 49, source: "Sent out specifically on a mission by a close friend or relative" },
        { min: 50, max: 52, source: "A bizarre, highly lucid dream" },
        { min: 53, max: 55, source: "The local temple calls you forward and delivers the quest" },
        { min: 56, max: 58, source: "A loose rumour picked up hanging around the city guard station" },
        { min: 59, max: 61, source: "Merchant’s Guild / prominent local traders posting a bounty" },
        { min: 62, max: 64, source: "An influential noble family directly entrusts you with the task" },
        { min: 65, max: 67, source: "A local event unexpectedly sparks a personal memory" },
        { min: 68, max: 70, source: "Sudden, overwhelming divine inspiration" },
        { min: 71, max: 73, source: "An overheard conversation between shifty individuals" },
        { min: 74, max: 76, source: "A passing overland traveller passing along news" },
        { min: 77, max: 77, source: "Entrusted with delivering a basic parcel... but something compels you to peek inside!" },
        { min: 78, max: 79, source: "Entrusted with delivering a basic parcel... but something compels you to peek inside!" },
        { min: 80, max: 83, source: "The town herald loudly shouting proclamations across the market square" },
        { min: 84, max: 87, source: "Direct orders matching protocols from higher command, your faction guild, or secret society" },
        { min: 88, max: 90, source: "A bloodstained note searched from a dead creature's remains" },
        { min: 91, max: 93, source: "You awake in the morning to find a crude map magically tattooed onto your skin!" },
        { min: 94, max: 97, source: "A sudden local natural disaster shifts the terrain, revealing something long hidden" },
        { min: 98, max: 100, source: "A close friend has just died as a direct result of this situation—you must avenge them!" }
    ]
});