window.tablesDatabase = window.tablesDatabase || [];

window.tablesDatabase.push({
    id: "regional-events",
    title: "Regional Backdrop Events",
    description: "Select an area context to determine major macro background events, societal shifts, or regional catastrophes.",
    type: "environment-matrix",
    environments: {
        Urban: [
            { min: 1, max: 2, result: "Wedding" },
            { min: 3, max: 4, result: "Name-giving day celebrations" },
            { min: 5, max: 6, result: "Public holiday" },
            { min: 7, max: 8, result: "Procession" },
            { min: 9, max: 10, result: "Harvest Festival" },
            { min: 11, max: 12, result: "Festival celebrating a god" },
            { min: 13, max: 14, result: "Celebration of a hero's return" },
            { min: 15, max: 16, result: "Market day" },
            { min: 17, max: 18, result: "Religious rally" },
            { min: 19, max: 20, result: "Official proclamation" },
            { min: 21, max: 22, result: "Amnesty" },
            { min: 23, max: 24, result: "Sudden storm / gale force winds" },
            { min: 25, max: 26, result: "Election / Change of civic leader" },
            { min: 27, max: 28, result: "Yearly local festival" },
            { min: 29, max: 30, result: "Assassination" },
            { min: 31, max: 32, result: "Performance of a play" },
            { min: 33, max: 34, result: "Musical concert" },
            { min: 35, max: 36, result: "Buskers performance" },
            { min: 37, max: 38, result: "Orator / storyteller" },
            { min: 39, max: 40, result: "Alefest" },
            { min: 41, max: 42, result: "Warrior exhibition" },
            { min: 43, max: 44, result: "Procession of royals" },
            { min: 45, max: 46, result: "Museum exhibition" },
            { min: 47, max: 48, result: "New building being opened" },
            { min: 49, max: 50, result: "Large army passing through town" },
            { min: 51, max: 52, result: "Gridlocked traffic" },
            { min: 53, max: 54, result: "Monster invasion!" },
            { min: 55, max: 56, result: "Conference of Wizards" },
            { min: 57, max: 58, result: "Graduation ceremony" },
            { min: 59, max: 60, result: "Traffic accident" },
            { min: 61, max: 62, result: "Freakish weather event" },
            { min: 63, max: 64, result: "Fire in Building" },
            { min: 65, max: 66, result: "Notable local figure assassinated" },
            { min: 67, max: 68, result: "Public duel" },
            { min: 69, max: 70, result: "Large scale fire" },
            { min: 71, max: 72, result: "Sinkhole opens" },
            { min: 73, max: 74, result: "Local army returning after recent skirmish" },
            { min: 75, max: 76, result: "Co-ordinated attack" },
            { min: 77, max: 78, result: "Protest" },
            { min: 79, max: 80, result: "Flood" },
            { min: 81, max: 82, result: "Martial law enforced (Reason?)" },
            { min: 83, max: 84, result: "Wild magic eruption" },
            { min: 85, max: 86, result: "Military conscription" },
            { min: 87, max: 88, result: "Revolution taking place (scale uncertain)" },
            { min: 89, max: 90, result: "Public Execution" },
            { min: 91, max: 92, result: "Storm" },
            { min: 93, max: 94, result: "Plague" },
            { min: 95, max: 96, result: "Earthquake" },
            { min: 97, max: 98, result: "Dimensional disruption" },
            { min: 99, max: 100, result: "Invading force" }
        ],
        Wilderness: [
            { min: 1, max: 2, result: "Landslide / Avalanche" },
            { min: 3, max: 4, result: "Earthquake" },
            { min: 5, max: 6, result: "Storm" },
            { min: 7, max: 8, result: "Druid gathering" },
            { min: 9, max: 10, result: "Religious pilgrimage" },
            { min: 11, max: 12, result: "Army encamped" },
            { min: 13, max: 14, result: "Sudden storm / gale force winds" },
            { min: 15, max: 16, result: "Overturned cart" },
            { min: 17, max: 18, result: "Flash flood" },
            { min: 19, max: 20, result: "Forest Fire" },
            { min: 21, max: 22, result: "Local humanoids having a festival" },
            { min: 23, max: 24, result: "Solar eclipse" },
            { min: 25, max: 26, result: "Hail (large hailstones?)" },
            { min: 27, max: 28, result: "Hurricane" },
            { min: 29, max: 30, result: "Tribal encounter" },
            { min: 31, max: 32, result: "Animal stampede" },
            { min: 33, max: 34, result: "Tree falls" },
            { min: 35, max: 36, result: "Boulder falls" },
            { min: 37, max: 38, result: "Unseasonable weather" },
            { min: 39, max: 40, result: "Lightning strikes" },
            { min: 41, max: 42, result: "Market" },
            { min: 43, max: 44, result: "Hunting Party" },
            { min: 45, max: 46, result: "Farmers harvesting crops" },
            { min: 47, max: 48, result: "Cart passing" },
            { min: 49, max: 50, result: "Refugees" },
            { min: 51, max: 52, result: "Massed Animals" },
            { min: 53, max: 54, result: "Toll demanded" },
            { min: 55, max: 56, result: "Distressed NPC" },
            { min: 57, max: 58, result: "Besieged settlement" },
            { min: 59, max: 60, result: "Come across structure" },
            { min: 61, max: 62, result: "Battle in progress" },
            { min: 63, max: 64, result: "Beast / Monster carcass" },
            { min: 65, max: 66, result: "Monster - easy encounter" },
            { min: 67, max: 68, result: "Monster - easy encounter" },
            { min: 69, max: 70, result: "Monster - medium encounter" },
            { min: 71, max: 72, result: "Monster - medium encounter" },
            { min: 73, max: 74, result: "Monster - hard encounter" },
            { min: 75, max: 76, result: "Monster - deadly encounter" },
            { min: 77, max: 78, result: "Volcanic eruption" },
            { min: 79, max: 80, result: "Plague (insect / vermin)" },
            { min: 81, max: 82, result: "Interdimensional Rift" },
            { min: 83, max: 84, result: "Army going to war" },
            { min: 85, max: 86, result: "Sinkhole Appears" },
            { min: 87, max: 88, result: "Appearance of Tyrant in the area" },
            { min: 89, max: 90, result: "Savage raiding party" },
            { min: 91, max: 92, result: "Marauding monster attacking village" },
            { min: 93, max: 94, result: "Undead awakening" },
            { min: 95, max: 100, result: "Unmarked Settlement" }
        ]
    }
});